name: Compile and Deploy to GitHub Page
on:
  push:
    branches:
      - source
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        ref: refs/heads/source

    - uses: actions/setup-node@v1
      with:
        node_version: '14.x'

    - name: Setup Git user info and env
      env:
        M_GITHUB_PAGES_TOKEN: ${{ secrets.M_GITHUB_PAGES_TOKEN }}
      run: |
        git config --global user.email "dsyslove@163.com"
        git config --global user.name "dsys"
        sed -i "s/M_GITHUB_PAGES_TOKEN/$M_GITHUB_PAGES_TOKEN/g" ./_config.yml
        npm install hexo -g
    - name: Install dependencies
      run: npm install
    - name: Compile and deploy blog
      run: hexo clean && hexo g && hexo d
